### ISSUE TITLE
使用时调用的脚本窗口一闪而过及解决方案

### ISSUE THREAD

**Issue by guoyida** [DavisZHANG-BlogOnly/dax-beautifier#1]
上午使用1.0.0的时候，调用的脚本一闪，通过录屏看到了报错原因（如果未来有个log去troubleshot更好）是因为找不到Microsoft.AnalysisService.XXXX几个文件。
去微软官网这里：
https://docs.microsoft.com/en-us/analysis-services/client-libraries
下载了MSOLAP，AMO，AMOMD几个文件并安装后，问题解决
如果有其他人遇到了类似问题可以尝试一下

**Comment by DavisZHANG-BlogOnly** [comment]
@guoyida Thanks! 已在1.0.1及后续版本中增加对应提示
