### ISSUE TITLE
Comitting Failed

### ISSUE THREAD

**Issue by nexus150** [DavisZHANG-BlogOnly/dax-beautifier#3]
im testing the tool with the september release of Power BI Desktop and the september demo file of Power BI team, my install was donde with Power BI Business Ops, i have AMO Install, the tool open and make the format calls but then before finish send the "Comitting Failed" message and the formulas formulas are not formatted, 

I tried running Power BI desktop as an administrator and as a user with the same result.

![image](https://user-images.githubusercontent.com/11592309/96337058-48521b00-1084-11eb-8419-0ab0957ef654.png)

**Comment by DavisZHANG-BlogOnly** [comment]
@nexus150 Sorry for the late reply. Are you enabled enhanced metadata for your PBI Desktop?

**Comment by nexus150** [comment]
Hello Davis, sorry for the late reply too, yes, the metadata enchaced is enabled, my power bi desktop comes from the installer and not from the windows store, is 64 Bits version.

**Comment by DavisZHANG-BlogOnly** [comment]
> Hello Davis, sorry for the late reply too, yes, the metadata enchaced is enabled, my power bi desktop comes from the installer and not from the windows store, is 64 Bits version.

@nexus150 Hi, I just test again with the latest version of PBID (2020-Oct 64bit) but haven't found this issues. I think you can do a simple test, importing data from you local excel file and writing a simple measure like "calculate(sum(),filter())" and then run the tool to see if it successful, that will help me to find out the reason for it, such as "out of memory" etc.
