### ISSUE TITLE
DAX Formatter API Change?

### ISSUE THREAD

**Issue by samaguire** [DavisZHANG-BlogOnly/dax-beautifier#5]
More of an improvement opportunity if you hadn't seen this yet.

https://github.com/otykier/TabularEditor/tree/2.13.0

```
BREAKING CHANGE
The FormatDax(string dax) script helper method has been deprecated. Please update your scripts to use the new syntax!. If you're using the method in an existing script, the execution will be throttled with a 5 second delay between calls! This was necessary to avoid overloading the DaxFormatter.com service. Also be aware that previous versions of Tabular Editor uses a different API, which might not work in the future.
```

**Comment by DavisZHANG-BlogOnly** [comment]
@samaguire Thank you very much for your reminder. I've noticed the risk of overload on the daxformatter.com, and although there are not many users of dax-beautifier, others may reuse the code. I'll switch to the [new request method ](https://docs.tabulareditor.com/FormatDax.html)in the next release.
